export const ON_GET_POSTS = "ON_GET_POSTS";
export const ON_FETCH_POSTS = "ON_FETCH_POSTS";
export const ON_GET_POST_COMMENTS = "ON_GET_POST_COMMENTS";
export const ON_FETCH_POST_COMMENTS = "ON_FETCH_POST_COMMENTS";
export const ON_ADD_POST_COMMENT = "ON_ADD_POST_COMMENT";
