export const ON_REQUEST_POSTS = "ON_REQUEST_POSTS";
export const ON_FETCH_POSTS = "ON_FETCH_POSTS";
export const ON_REQUEST_POST_COMMENTS = "ON_REQUEST_POST_COMMENTS";
export const ON_FETCH_POST_COMMENTS = "ON_FETCH_POST_COMMENTS";
export const ON_ADD_POST_COMMENT = "ON_ADD_POST_COMMENT";
export const ON_SET_PAGES_AMOUNT = "ON_SET_PAGES_AMOUNT";
export const ON_SET_PAGE = "ON_SET_PAGE";
